- 현재 작업 공간을 foo.mat라는 MAT 파일로 저장하려면 다음 명령을 사용하세요.  
'>> save foo


- MATLAB에서 새로운 문제로 넘어가기 위해 작업 공간을 정리해야 할 경우가 있습니다. clear 함수를 사용하면 작업 공간에 있는 변수를 모두 없앨 수 있습니다.  
'>> clear


- load 명령을 사용하면 MAT 파일로부터 변수를 불러올 수 있습니다.  
'>> load foo



- 변수 data가 작업 공간에 추가된 것을 확인할 수 있습니다. 변수 이름을 입력하면 그 변수의 내용을 볼 수 있습니다.  
'>> myvar


- clear 함수는 작업 공간의 내용을 지웁니다. clc를 사용하면 명령 창의 내용을 지울 수 있습니다.  
'>>clc


- MATLAB을 닫으면 작업 공간의 내용이 지워집니다. MAT 파일을 사용하여 변수를 저장할 수 있습니다. 그러면 MATLAB을 다시 열 때 변수를 작업 공간으로 불러올 수 있습니다.

    일부 변수만 불러오거나 저장하려면 함수에 두 개의 입력값을 사용하면 됩니다. 파일 myData.mat로부터 변수 m만 불러와 보세요.  
    '>> load myData m

    그런 다음 변수 m을 justm.mat라는 새 MAT 파일로 저장해 보세요.  
    '>> save justm m


- MATLAB은 여러 내장 상수들을 제공합니다. 예를 들어, π를 나타내기 위해 pi를 사용합니다.  
'>> a = pi  
a = 3.1416  
또한 π를 소수점 이하 네 자릿수까지만 표시하지만 내부적으로는 더 높은 정밀도 표현을 사용합니다.


- MATLAB에는 abs(절댓값) 및 eig(고유값 계산)와 같은 다양한 내부 함수가 있습니다.  
'>> a = sin(-5)  
a = 0.9589  
MATLAB은 표준 수학 표기법과 비슷한 방식으로 괄호를 사용하여 입력값을 함수에 전달합니다.


- sqrt 함수를 사용하여 -9의 제곱근을 계산하세요. 그 결과를 변수 z에 할당하세요.    
'>> z = sqrt(-9)  
z = 0.0000 + 3.0000i

    참고로 계산된 해에 허수 i가 포함된 것을 볼 수 있습니다. 이는 MATLAB에 내장된 상수입니다.

    명령 창에는 소수점 이하 네 자릿수까지만 표시됩니다. format 함수를 사용하여 표시되는 정밀도를 제어할 수 있습니다.

    format long을 입력하고 x의 값을 표시해 보세요. 
    '>> format long  
    '>> z  

    z = 0.000000000000000 + 3.000000000000000i

    디폴트 표시로 되돌리려면

    format short를 입력합니다.


#### 행렬과 배열

MATLAB은 "Matrix Laboratory"의 약어입니다. 다른 프로그래밍 언어에서는 대부분 수를 한 번에 하나씩 다루지만, MATLAB®은 행렬이나 배열 단위로 연산을 수행합니다.

MATLAB의 모든 변수는 데이터형에 관계없이 다차원 배열입니다. 행렬은 선형 대수에 주로 사용되는 2차원 배열입니다.

###### 배열 생성
- 행 하나에 네 개의 요소가 포함된 배열을 만들려면 요소를 쉼표(,)나 공백으로 구분하십시오.

    x = [7 9]      (1x2행렬)  
    x = [3 10 5]      (1x3행렬)  
    x = [8; 2; -4]      (3x1행렬)  
    x = [5 6 7; 8 9 10]      (2x3행렬)  


- MATLAB에서는 대괄호 내에서 계산을 수행할 수 있습니다.  
    x = [abs(-4) 4^2]  
    x = 4    16      (1x2행렬)  
    

- 길이가 긴 벡터를 만들 경우 숫자를 일일이 입력하는 것은 실용적이지 않습니다. 그 대신에 : 연산자를 사용하여 시작점과 끝점만 지정하면 균일한 간격의 요소로 구성된 벡터를 간단히 만들 수 있습니다.  
    y = 5:8  
    y = 5    6    7    8  (1x4행렬)  
    콜론 연산자를 사용하는 경우에는 대괄호가 필요하지 않습니다.
    
    
- 연산자의 디폴트 간격 값은 1로 지정되어 있지만, 아래와 같이 특정 간격을 지정할 수도 있습니다.  
    x = 20:2:26  
    x = 20    22    24    26  (1x4행렬)  
    
    
- 만들고자 하는 벡터에서 각 요소 간 간격이 아니라 원하는 요소의 개수를 이미 알고 있는 경우 linspace 함수를 사용할 수 있습니다.
    linspace(first,last,number_of_elements)

    linspace 함수에 대한 입력값은 쉼표(,)를 사용하여 구분해야 합니다.  
    x = linspace(0,1,5)  
    x = 0    0.250    0.500    0.750    1.000  
    
    
- linspace 연산자와 : 연산자는 모두 행 벡터를 만듭니다. 하지만 전치 연산자(')를 사용하면 행 벡터를 열 벡터로 변환할 수 있습니다.  
    x = 1:3;  
    x = x'  
    x = 
        1  
        2  
        3  
        
- 행 벡터를 만들고 이를 전치하는 작업을 한 줄에서 모두 수행하여 한 번의 명령으로 열 벡터를 만들 수 있습니다. 참고로 여기서는 괄호를 사용하여 연산자의 실행 순위를 지정했습니다.  
x = (1:2:5)'


- 난수로 구성된 행렬과 같이 흔히 사용되는 행렬을 쉽게 만들 수 있도록 MATLAB에는 다양한 함수가 있습니다.  
    x = rand(2)  
    x = 
        0.8147    0.1270
        0.9058    0.9134  
    참고로 명령 rand(2)에서 2는 난수로 구성된 2x2 행렬이 출력되도록 지정합니다.
    
    
- 다수의 행렬 생성 함수에서 하나의 숫자를 입력값으로 사용하면 정사각 행렬(nxn)을 만들 수 있고 두 개의 숫자를 입력값으로 사용하면 비정사각 행렬을 만들 수 있습니다.  
    x = rand(2)  
    x = 
        0.8147    0.1270
        0.9058    0.9134

    x = rand(2,3)  
    x = 
        0.6324    0.2785    0.9575
        0.0975    0.5469    0.9649
        
        
- zeros 함수를 사용하여 6개 행과 3개 열을 가지며, 요소가 모두 0인 행렬(6x3)을 만들고 그 결과를 변수 x에 할당하세요.  
    x = zeros(6,3)



- 기존 행렬의 크기는 어떻게 확인할 수 있을까요? size 함수를 사용하면 됩니다.  
    size(x)

    또한, 코드 한 줄로 기존 행렬과 동일한 크기의 행렬을 만들 수도 있습니다.  
    rand(size(x))
    


- 행, 열 인덱싱을 사용하여 배열 내 값을 추출할 수 있습니다.  
y = A(5,7)  
이 구문은 A의 5번째 행, 7번째 열의 값을 추출한 후 그 결과를 변수 y에 할당합니다.



- MATLAB 키워드 end를 행 인덱스 또는 열 인덱스로 사용하면 마지막 요소를 참조할 수 있습니다.  
y = A(end,2)



- 참고로 키워드 end에 아래와 같이 산술 연산을 적용할 수 있습니다. 예를 들면 다음과 같습니다.    
y = A(end-1,end-2)


- 한 행렬에 대해 하나의 인덱스만 사용할 경우 각각의 열을 순서대로 아래 방향으로 순회하게 됩니다. 하나의 인덱스를 사용하여 데이터의 8번째 요소를 추출해 보세요.  
x = data(8)


- 콜론 연산자(:)를 인덱스로 사용하면 해당 차원의 모든 요소를 지정하게 됩니다.  
x = A(2,:)  
A의 두 번째 행에 있는 모든 요소를 포함하는 행 벡터를 만듭니다.


- 콜론 연산자는 특정 범위의 값을 참조할 수 있습니다.   
다음 구문은 행렬 A의 첫 번째 행, 두 번째 행 및 세 번째 행을 포함하는 행렬을 만듭니다.  
x = A(1:3,:)


- 인덱스는 연속되지 않은 숫자를 사용해도 됩니다. density의 첫 번째 요소, 세 번째 요소 및 여섯 번째 요소를 추출해 보세요.  
p = density(1:2:6,:)


- 문자를 사용하면 데이터 내 모든 열을 추출할 수 있습니다.  
v2 = data(:,end)


- 인덱싱과 할당을 함께 사용하면 변수의 요소를 변경할 수 있습니다.  
A(2) = 11


- data의 첫 번째 행, 마지막 열의 요소 값을 0.5로 변경하세요.  
data(1,end) = 0.5


- 인덱싱과 할당을 함께 사용하여 배열의 값을 또다른 요소의 값과 같게 변경할 수도 있습니다. 예를 들어, 다음 코드는 x(1)의 값을 x(2)로 변경합니다.  
x(1) = x(2)
data(:,1) = data(:,2)


- 배열 내 모든 요소에 스칼라 값을 더할 수 있습니다.  
y = x + 2


- 동일한 크기를 갖는 두 배열을 서로 더할 수 있습니다.  
z = x + y


- 배열 내 모든 요소에 스칼라 값을 곱하거나 나눌 수 있습니다.  
z = 2*x  
y = x/3  


- 벡터의 최댓값은 max 함수를 사용하여 구할 수 있습니다.  
xMax = max(x)


- round 함수를 사용하여 반올림된 평균 부피 va를 포함하는 변수 vr을 만드세요.  
vr = round(va)


- '*' 연산자는 행렬 곱셈을 수행합니다. 따라서 *를 사용하여 크기가 동일한 두 개의 벡터를 곱할 경우 내부 차원이 동일하지 않으므로 아래와 같은 오류 메시지가 표시됩니다.  
z = [3 4] * [10 20]  
Error using  *   
Incorrect dimensions for matrix multiplication.   

    반대로 .* 연산자는 요소별 곱셈을 수행하므로, 이 연산자를 사용하면 크기가 동일한 두 배열 내 대응하는 요소끼리 곱할 수 있게 됩니다.  
    z = [3 4] .* [10 20]  
    z =   
    30    80  
    
    
    density와 va에 대해 요소별 곱셈 연산을 수행하고 그 결과를 변수 mass에 저장하세요.  
    mass = density .* va
    
    
    서로 계산 가능한 크기들이 있습니다. 예를 들어, 다음을 실행해 보세요.  
    x = [1 2;3 4;5 6; 7 8].*[1;2;3;4]
    x = [1 2;6 8;15 18; 28 32]

### 기본 연산에 대해 호환되는 배열 크기


MATLAB®의 대부분의 이진(두 개 입력값) 연산자와 함수는 호환되는 크기의 숫자형 배열을 지원합니다. 모든 차원에 대해 입력값의 차원 크기가 동일하거나 차원 크기 중 하나가 1인 경우 두 입력값의 크기는 호환됩니다. 가장 간단한 경우를 들면, 두 배열의 크기가 정확히 동일하거나 한쪽이 스칼라인 경우 두 배열 크기는 서로 호환됩니다. 요소별 연산 또는 함수를 실행하는 동안 MATLAB은 호환되는 크기의 배열을 동일한 크기가 되도록 암시적으로 확장합니다.

호환되는 크기의 입력값
##### 2차원 입력값
다음은 크기가 호환되는 스칼라, 벡터, 행렬의 몇 가지 조합입니다.

- 두 입력값의 크기가 정확히 동일한 경우.

![이미지](https://kr.mathworks.com/help/matlab/matlab_prog/implicit_3.png)

- 한쪽 입력값이 스칼라인 경우.

![이미지](https://kr.mathworks.com/help/matlab/matlab_prog/implicit_4.png)

- 한쪽 입력값이 행렬이고 다른 쪽 입력값은 행 개수가 동일한 열 벡터인 경우.

![이미지](https://kr.mathworks.com/help/matlab/matlab_prog/implicit_1.png)

- 한쪽 입력값이 열 벡터이고 다른 쪽 입력값은 행 벡터인 경우.

![이미지](https://kr.mathworks.com/help/matlab/matlab_prog/implicit_2.png)

#### 다차원 배열
MATLAB의 모든 배열은 크기가 1인 후행 차원들을 갖습니다. 즉, 다차원 배열의 경우 3x4 행렬은 크기가 3x4x1x1x1인 행렬과 같습니다. 크기가 호환되는 다차원 배열에 대한 예는 다음과 같습니다.

- 한쪽 입력값이 행렬이고 다른 쪽 입력값은 행 개수와 열 개수가 이와 동일한 3차원 배열인 경우.

![이미지](https://kr.mathworks.com/help/matlab/matlab_prog/implicit_5.png)

- 한쪽 입력값이 행렬이고 다른 쪽 입력값은 3차원 배열인 경우. 차원이 모두 동일하거나 한쪽이 1입니다.

![이미지](https://kr.mathworks.com/help/matlab/matlab_prog/implicit_6.png)

#### 빈 배열
차원 크기가 0인 배열이나 빈 배열의 경우 동일한 규칙이 적용됩니다. 출력값의 크기는 1이 아닌 차원의 크기에 의해 결정됩니다. 즉, 크기가 0인 차원은 다른 배열의 크기가 1 또는 0인 차원과 쌍을 이루어야 하며 출력값의 차원 크기는 0입니다.

     A: 1-by-0          
     B: 3-by-1     
     Result: 3-by-0

### 호환되지 않는 크기의 입력값
호환되지 않는 크기의 입력값은 동일한 크기가 되도록 암시적으로 확장할 수 없습니다. 예를 들면 다음과 같습니다.

- 차원 크기가 서로 일치하지 않고 어느 쪽도 1이 아닌 경우.

    A: 3-by-2  
    B: 4-by-2  


- 길이가 서로 동일하지 않은 2개의 비 스칼라 행 벡터.

    A: 1-by-3  
    B: 1-by-4  

#### 예제  
행렬에서 벡터 빼기  
벡터-행렬 연산을 단순화하려면 sum, mean, min 등의 차원 함수에서 암시적 확장을 사용하십시오.  

예를 들어, 행렬의 각 열에 대한 평균값을 계산한 다음 각 요소에서 평균값을 뺍니다.  

A = magic(3)  
A =

     8     1     6
     3     5     7
     4     9     2  
     
C = mean(A)  
C =  

     5     5     5  
     
A - C  
ans =

     3    -4     1
    -2     0     2
    -1     4    -3  
    
    
#### 행 벡터와 열 벡터 더하기
행 벡터와 열 벡터는 크기가 서로 호환되며, 이 두 벡터에 대한 연산을 수행하면 그 결과로 행렬이 반환됩니다.

예를 들어, 행 벡터와 열 벡터를 더해 보겠습니다. 결과는 bsxfun(@plus,a,b)와 동일합니다.

a = [1 2 3 4]  
ans =

     1     2     3     4  
     
b = [5; 6; 7]  
ans =

     5
     6
     7  
     
a + b  
ans =

     6     7     8     9
     7     8     9    10
     8     9    10    11

- 배열에 size 함수를 적용하여 배열 크기를 포함하는 하나의 출력 변수를 생성할 수 있습니다.  
s = size(x)


- 행렬에 size 함수를 적용하여 1개 또는 2개의 출력 변수를 생성할 수 있습니다. 둘 이상의 출력값을 구하려면 대괄호([ ])를 사용합니다.  
[xrow,xcol] = size(x)


- max 함수를 사용하여 벡터의 최댓값과 이에 해당하는 인덱스 값을 확인할 수 있습니다. max 함수의 첫 번째 출력값이 입력 벡터의 최댓값입니다. 2개의 출력값을 지정하여 호출할 때는 두 번째 출력값이 인덱스 값입니다.  
[xMax,idx] = max(x)


- 함수의 두 번째 출력값만 필요한 경우 물결표(~)를 사용하여 특정 출력값을 무시할 수 있습니다.  

    예를 들어, 벡터의 최댓값을 포함하는 인덱스만 필요한 경우 다음과 같이 합니다.  
    density = data(:,2)  
    [~,ivMax] = max(v2)  
    densityMax = density(ivMax)  
    
    v2에서 최솟값의 인덱스 값을 구해 보세요. 이 인덱스를 사용하여 density에서 값을 추출해 보세요.  
    density = data(:,2)
    [~, ivMin] = min(v2)
    density = density(ivMin)